-- =============================================================================
-- Ancra – Initial Schema
-- =============================================================================
-- All monetary amounts are stored in kobo (int8 / int64).
-- All primary keys are UUIDs generated by the application layer.
-- =============================================================================

-- Enable pgcrypto for gen_random_uuid() if not already enabled.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- customers
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id         UUID        PRIMARY KEY,
    kyc_tier   SMALLINT    NOT NULL DEFAULT 1 CHECK (kyc_tier BETWEEN 1 AND 3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- identity_versions  (point-in-time display names)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity_versions (
    id             UUID        PRIMARY KEY,
    customer_id    UUID        NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    display_name   TEXT        NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to   TIMESTAMPTZ,                      -- NULL means currently active
    CONSTRAINT no_overlapping_active UNIQUE (customer_id, effective_to)
                                                     -- (customer_id, NULL) is unique per standard SQL
);

CREATE INDEX IF NOT EXISTS idx_identity_versions_customer
    ON identity_versions (customer_id, effective_from DESC);

-- ---------------------------------------------------------------------------
-- virtual_accounts
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE account_status AS ENUM ('active', 'closed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS virtual_accounts (
    id                  UUID           PRIMARY KEY,
    customer_id         UUID           NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    account_ref         TEXT           NOT NULL UNIQUE,
    bank_account_number TEXT           NOT NULL,
    bank_account_name   TEXT           NOT NULL,
    status              account_status NOT NULL DEFAULT 'active',
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- Indexed for fast webhook resolution: account_number → virtual_account.
CREATE UNIQUE INDEX IF NOT EXISTS idx_virtual_accounts_number
    ON virtual_accounts (bank_account_number);

CREATE INDEX IF NOT EXISTS idx_virtual_accounts_customer
    ON virtual_accounts (customer_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- system_accounts  (pool, suspense, fees, returns_clearing)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_accounts (
    id   UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- Seed the four mandatory system accounts.
INSERT INTO system_accounts (id, name) VALUES
    (gen_random_uuid(), 'pool'),
    (gen_random_uuid(), 'suspense'),
    (gen_random_uuid(), 'fees'),
    (gen_random_uuid(), 'returns_clearing')
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- ledger_entries  (append-only double-entry ledger)
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE entry_direction AS ENUM ('debit', 'credit');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS ledger_entries (
    id           UUID            PRIMARY KEY,
    account_id   UUID            NOT NULL,              -- virtual_accounts.id OR system_accounts.id
    direction    entry_direction NOT NULL,
    amount       BIGINT          NOT NULL CHECK (amount > 0),
    currency     CHAR(3)         NOT NULL DEFAULT 'NGN',
    txn_group_id UUID            NOT NULL,              -- groups the two legs of a double-entry pair
    external_ref TEXT,                                  -- Nomba transactionId
    entry_type   TEXT            NOT NULL,              -- inbound_credit | pool_liability | transfer_out | fee | …
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- No UPDATE or DELETE should ever touch this table.
-- Application-layer convention; enforced by only granting INSERT + SELECT.

CREATE INDEX IF NOT EXISTS idx_ledger_account_created
    ON ledger_entries (account_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ledger_txn_group
    ON ledger_entries (txn_group_id);

CREATE INDEX IF NOT EXISTS idx_ledger_external_ref
    ON ledger_entries (external_ref)
    WHERE external_ref IS NOT NULL;

-- ---------------------------------------------------------------------------
-- processed_events  (idempotency for inbound Nomba webhooks)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS processed_events (
    transaction_id TEXT        PRIMARY KEY,
    request_id     TEXT,
    received_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- reconciliation_runs
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE recon_status AS ENUM ('ok', 'mismatch');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS reconciliation_runs (
    id                    UUID         PRIMARY KEY,
    run_at                TIMESTAMPTZ  NOT NULL DEFAULT now(),
    nomba_wallet_balance  BIGINT       NOT NULL,   -- kobo
    computed_pool_balance BIGINT       NOT NULL,   -- kobo
    delta                 BIGINT       NOT NULL,   -- nomba_wallet_balance - computed_pool_balance
    status                recon_status NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_recon_runs_run_at
    ON reconciliation_runs (run_at DESC);

-- ---------------------------------------------------------------------------
-- webhook_deliveries  (outbound developer webhook queue)
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE webhook_status AS ENUM ('pending', 'delivered', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id            UUID           PRIMARY KEY,
    event_type    TEXT           NOT NULL,
    payload       JSONB          NOT NULL,
    status        webhook_status NOT NULL DEFAULT 'pending',
    attempts      SMALLINT       NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_pending
    ON webhook_deliveries (status, next_retry_at)
    WHERE status = 'pending';
